# Generated by Django 5.0.3 on 2024-03-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("food", "food"),
                    ("life style", "life style"),
                    ("travel", "travel"),
                ],
                default="travel",
                max_length=100,
            ),
        ),
    ]
