# Generated by Django 5.0.3 on 2024-03-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_visibility"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="visibility", new_name="catagory",
        ),
    ]
